"""Add quantity to borrow requests

Revision ID: dc42f5515650
Revises: 82eb6c2578e0
Create Date: 2026-07-22 10:14:52.838104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc42f5515650'
down_revision: Union[str, Sequence[str], None] = '82eb6c2578e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_requests', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrow_requests', 'quantity')
    # ### end Alembic commands ###
